# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - "main"
      - "features/**"
  pull_request:
  workflow_dispatch:

jobs:
  build-old:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal -- --filter-not-namespace 'MstTrx2*'

    - name: Publish test report
      uses: dorny/test-reporter@v2
      with:
        name: Test report
        path: ./**/TestResults/*.trx
        reporter: dotnet-trx
        use-actions-summary: 'true'

  build-new:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal -- --filter-not-namespace 'MstTrx2*'

    - name: Publish test report
      uses: OlesGalatsan/test-reporterg@bugfix/empty-trx-test-definitions
      with:
        name: Test report
        path: ./**/TestResults/*.trx
        reporter: dotnet-trx
        use-actions-summary: 'true'
